// Port of ru/alientransporter/Assets.as
//
// DEVIATION: the original returns the embedded library classes (`Vector.<Class>`); here the list holds the
// symbol names (strings) of assets/manifest.json, in the same order. 413 names.

export class Assets {
  constructor() {
    // super();
  }

  static getGraphics(): string[] {
    return [
      'Barrel_mc', 'BarrelFragment_mc', 'BarrelExp_mc', 'BarrelExpFragment_mc', 'BoxSmall_mc',
      'BoxSmallFragment_mc', 'BoxBig_mc', 'BoxBigFragment_mc', 'Rock01_mc', 'Rock02_mc', 'Rock03_mc',
      'Rock04_mc', 'Rock05_mc', 'Rock06_mc', 'Rock07_mc', 'RockFragment01_mc', 'RockFragment02_mc',
      'RockFragment03_mc', 'RockFragment04_mc', 'RockFragment05_mc', 'RockFragment06_mc',
      'Shuttle01PassBlue_mc', 'Shuttle01PassGreen_mc', 'Shuttle01PassOrange_mc', 'Shuttle01PassPink_mc',
      'Missile_mc', 'MissileFragment_mc', 'Shuttle01Body_mc', 'Shuttle01EngineLeft_mc',
      'Shuttle01EngineRight_mc', 'Shuttle01LegLeft_mc', 'Shuttle01LegRight_mc', 'Shuttle01Back_mc',
      'Shuttle01Frag01_mc', 'Shuttle01Frag02_mc', 'Shuttle01Frag03_mc', 'Shuttle01Frag04_mc',
      'Shuttle01Frag05_mc', 'Shuttle01Column_mc', 'Engine01Column_mc', 'Shuttle02Body_mc',
      'Shuttle02EngineLeft_mc', 'Shuttle02EngineRight_mc', 'Shuttle02LegLeft_mc', 'Shuttle02LegRight_mc',
      'Shuttle02Back_mc', 'Shuttle02Frag01_mc', 'Shuttle02Frag02_mc', 'Shuttle02Frag03_mc',
      'Shuttle02Frag04_mc', 'Shuttle02Frag05_mc', 'Shuttle02Column_mc', 'Engine02Column_mc',
      'Shuttle03Body_mc', 'Shuttle03EngineLeft_mc', 'Shuttle03EngineRight_mc', 'Shuttle03LegLeft_mc',
      'Shuttle03LegRight_mc', 'Shuttle03Back_mc', 'Shuttle03Frag01_mc', 'Shuttle03Frag02_mc',
      'Shuttle03Frag03_mc', 'Shuttle03Frag04_mc', 'Shuttle03Frag05_mc', 'Shuttle03Column_mc',
      'Engine03Column_mc', 'Shuttle04Body_mc', 'Shuttle04EngineLeft_mc', 'Shuttle04EngineRight_mc',
      'Shuttle04LegLeft_mc', 'Shuttle04LegRight_mc', 'Shuttle04Back_mc', 'Shuttle04Frag01_mc',
      'Shuttle04Frag02_mc', 'Shuttle04Frag03_mc', 'Shuttle04Frag04_mc', 'Shuttle04Frag05_mc',
      'Shuttle04Column_mc', 'Engine04Column_mc', 'PassengerGreen01Idle_mc', 'PassengerGreen02Idle_mc',
      'PassengerGreen03Idle_mc', 'PassengerGreen04Idle_mc', 'PassengerGreen05Idle_mc',
      'PassengerGreen01Walk_mc', 'PassengerGreen02Walk_mc', 'PassengerGreen03Walk_mc',
      'PassengerGreen04Walk_mc', 'PassengerGreen05Walk_mc', 'PassengerGreen01Action_mc',
      'PassengerGreen02Action_mc', 'PassengerGreen03Action_mc', 'PassengerGreen04Action_mc',
      'PassengerGreen05Action_mc', 'PassengerBlue01Idle_mc', 'PassengerBlue02Idle_mc',
      'PassengerBlue03Idle_mc', 'PassengerBlue04Idle_mc', 'PassengerBlue05Idle_mc', 'PassengerBlue01Walk_mc',
      'PassengerBlue02Walk_mc', 'PassengerBlue03Walk_mc', 'PassengerBlue04Walk_mc', 'PassengerBlue05Walk_mc',
      'PassengerBlue01Action_mc', 'PassengerBlue02Action_mc', 'PassengerBlue03Action_mc',
      'PassengerBlue04Action_mc', 'PassengerBlue05Action_mc', 'PassengerPink01Idle_mc',
      'PassengerPink02Idle_mc', 'PassengerPink03Idle_mc', 'PassengerPink04Idle_mc', 'PassengerPink05Idle_mc',
      'PassengerPink01Walk_mc', 'PassengerPink02Walk_mc', 'PassengerPink03Walk_mc', 'PassengerPink04Walk_mc',
      'PassengerPink05Walk_mc', 'PassengerPink01Action_mc', 'PassengerPink02Action_mc',
      'PassengerPink03Action_mc', 'PassengerPink04Action_mc', 'PassengerPink05Action_mc',
      'PassengerOrange01Idle_mc', 'PassengerOrange02Idle_mc', 'PassengerOrange03Idle_mc',
      'PassengerOrange04Idle_mc', 'PassengerOrange05Idle_mc', 'PassengerOrange01Walk_mc',
      'PassengerOrange02Walk_mc', 'PassengerOrange03Walk_mc', 'PassengerOrange04Walk_mc',
      'PassengerOrange05Walk_mc', 'PassengerOrange01Action_mc', 'PassengerOrange02Action_mc',
      'PassengerOrange03Action_mc', 'PassengerOrange04Action_mc', 'PassengerOrange05Action_mc',
      'FragBodyBlue_mc', 'FragHandLeftBlue_mc', 'FragHandRightBlue_mc', 'FragLegLeftBlue_mc',
      'FragLegRightBlue_mc', 'FragHeadBlue_mc', 'FragBodyPink_mc', 'FragHandLeftPink_mc',
      'FragHandRightPink_mc', 'FragLegLeftPink_mc', 'FragLegRightPink_mc', 'FragHeadPink_mc',
      'FragBodyGreen_mc', 'FragHandLeftGreen_mc', 'FragHandRightGreen_mc', 'FragLegLeftGreen_mc',
      'FragLegRightGreen_mc', 'FragHeadGreen_mc', 'FragBodyOrange_mc', 'FragHandLeftOrange_mc',
      'FragHandRightOrange_mc', 'FragLegLeftOrange_mc', 'FragLegRightOrange_mc', 'FragHeadOrange_mc',
      'FragBandage_mc', 'FragCrown_mc', 'FragMage_mc', 'FragPirate_mc', 'FragRobin_mc', 'SmokeEffect01_mc',
      'SmokeEffect02_mc', 'EngineFireEffect01_mc', 'EngineFireEffect02_mc', 'DustEffect01_mc',
      'DustEffect02_mc', 'Indicator01Color01_mc', 'Indicator01Color02_mc', 'Indicator01Color03_mc',
      'Indicator01Color04_mc', 'Indicator01Color05_mc', 'Indicator02Color01_mc', 'Indicator02Color02_mc',
      'Indicator02Color03_mc', 'Indicator02Color04_mc', 'Indicator02Color05_mc', 'Indicator03Color01_mc',
      'Indicator03Color02_mc', 'Indicator03Color03_mc', 'Indicator03Color04_mc', 'Indicator03Color05_mc',
      'Indicator04Color01_mc', 'Indicator04Color02_mc', 'Indicator04Color03_mc', 'Indicator04Color04_mc',
      'Indicator04Color05_mc', 'Coin_mc', 'Repair_mc', 'Fuel_mc', 'Heart_mc', 'Trophy_mc', 'HouseFront01_mc',
      'NotifyAttention_mc', 'NotifyLove_mc', 'NotifyFail_mc', 'BlinkerRed_mc', 'BlinkerGreen_mc',
      'BlinkerOff_mc', 'TransporterWheel01_mc', 'TransporterWheel02_mc', 'FuelIndicatorBG_mc',
      'FuelIndicatorRed_mc', 'FuelIndicatorYellow_mc', 'FuelIndicatorGreen_mc', 'ScreenFade_mc',
      'PassengerBar_mc', 'PassengerBarRoller_mc', 'PassengerBarIcons_mc', 'ShuttleBarLeftBG_mc',
      'ShuttleBarLeftRoller_mc', 'ShuttleBarRightBG_mc', 'ShuttleBarRightRoller_mc',
      'ShuttleHull01Color01_mc', 'ShuttleHull01Color02_mc', 'ShuttleHull01Color03_mc',
      'ShuttleHull01Color04_mc', 'ShuttleHull01Color05_mc', 'ShuttleHull02Color01_mc',
      'ShuttleHull02Color02_mc', 'ShuttleHull02Color03_mc', 'ShuttleHull02Color04_mc',
      'ShuttleHull02Color05_mc', 'ShuttleHull03Color01_mc', 'ShuttleHull03Color02_mc',
      'ShuttleHull03Color03_mc', 'ShuttleHull03Color04_mc', 'ShuttleHull03Color05_mc',
      'ShuttleHull04Color01_mc', 'ShuttleHull04Color02_mc', 'ShuttleHull04Color03_mc',
      'ShuttleHull04Color04_mc', 'ShuttleHull04Color05_mc', 'LivesIcon_mc', 'CoinsIcon_mc',
      'Player1PressUp_mc', 'Player2PressUp_mc', 'Player1GameOver_mc', 'Player2GameOver_mc', 'BtnMusicOn_mc',
      'BtnMusicOff_mc', 'BtnSoundOn_mc', 'BtnSoundOff_mc', 'BtnPause_mc', 'BtnArmor_mc',
      'BtnArmorLogoSmall_mc', 'TitleLevel_mc', 'TitleLevelNumber_mc', 'MissionBar_mc', 'BtnGet_mc',
      'MissionPopupBG_mc', 'IconMagnet_mc', 'IconMagnetSmall_mc', 'IconRandom_mc', 'IconRandomSmall_mc',
      'IconPassengerBlue_mc', 'IconPassengerOrange_mc', 'IconPassengerPink_mc', 'IconPassengerPirate_mc',
      'IconPassengerRobin_mc', 'IconPassengerMage_mc', 'IconPassengerKing_mc', 'IconShuttlePink_mc',
      'IconShuttleBlue_mc', 'IconShuttleGreen_mc', 'IconShuttle02_mc', 'IconShuttle03_mc',
      'IconShuttle04_mc', 'IconPassengerBlueSmall_mc', 'IconPassengerOrangeSmall_mc',
      'IconPassengerPinkSmall_mc', 'IconPassengerPirateSmall_mc', 'IconPassengerRobinSmall_mc',
      'IconPassengerMageSmall_mc', 'IconPassengerKingSmall_mc', 'IconShuttlePinkSmall_mc',
      'IconShuttleBlueSmall_mc', 'IconShuttleGreenSmall_mc', 'IconShuttle02Small_mc',
      'IconShuttle03Small_mc', 'IconShuttle04Small_mc', 'IconRepair_mc', 'IconRepairSmall_mc', 'IconFuel_mc',
      'IconFuelSmall_mc', 'IconHeart_mc', 'IconHeartSmall_mc', 'IconTrophy_mc', 'IconTrophySmall_mc',
      'Blow_mc', 'SparkWhite01_mc', 'SparkWhite02_mc', 'Wave01_mc', 'Wave02_mc', 'OilEffect01_mc',
      'SmokeParticle01_mc', 'SmokeParticle02_mc', 'SparkGround01_mc', 'SparkYellow_mc', 'FireEffect01_mc',
      'FireEffect02_mc', 'SmokeParticle03_mc', 'SmokeParticle04_mc', 'FlashYellow_mc', 'FlashYellow02_mc',
      'ExplosionFire01_mc', 'ExplosionSmoke01_mc', 'ExplosionSmoke02_mc', 'ParticleYellow_mc',
      'PortalSmoke_mc', 'PortalBG_mc', 'FlashWhite_mc', 'SparkBlue01_mc', 'SparkBlue02_mc',
      'MagicFlyBlue_mc', 'MagicLeafPurple_mc', 'MagicLeafYellow_mc', 'SparkBlue_mc', 'SparkPink_mc',
      'FlashSmallBlue_mc', 'FlashPurple_mc', 'StarParticle_mc', 'FadeEffectShow_mc', 'FadeEffectHide_mc',
      'BtnShadowBig_mc', 'BtnShadowSmall_mc', 'MainMenuBG_mc', 'BtnPlay_mc', 'BtnMoreGames_mc',
      'BtnCredits_mc', 'BtnArmorGames_mc', 'BtnFaceBook_mc', 'BtnTwitter_mc', 'Copyright_mc',
      'CreditsScreenBG_mc', 'BtnAnton_mc', 'BtnAhura_mc', 'BtnWesley_mc', 'BtnPatreon_mc',
      'SelectLevelBG_mc', 'BtnLevelBasic_mc', 'BtnLevelBonus_mc', 'BtnMainMenu_mc', 'BtnShip_mc',
      'BtnStar_mc', 'BtnGarage_mc', 'BtnAchievements_mc', 'BtnDelete_mc', 'BtnCancel_mc', 'ConfirmTextEN_mc',
      'NotifyIconLeft_mc', 'MissionCompleteLight01_mc', 'MissionCompleteLight02_mc', 'PauseTextEN_mc',
      'EffectsTextEN_mc', 'QualityTextEN_mc', 'FancyTextEN_mc', 'QuickTextEN_mc', 'PauseScreenBG_mc',
      'PausePopupBG_mc', 'BtnSwitchOn_mc', 'BtnSwitchOff_mc', 'GameOverTextEN_mc', 'GameOverPopupBG_mc',
      'CompleteLevelBG_mc', 'BtnRestart_mc', 'BtnApply_mc', 'StarTiny_mc', 'StarMiddle_mc', 'StarBig_mc',
      'BgLine_mc', 'ColumnBar_mc', 'TitlePrevRecord_mc', 'TitleP1_mc', 'TitleP2_mc', 'GarageBG_mc',
      'BtnYellow_mc', 'BtnRed_mc', 'BtnPink_mc', 'BtnBlue_mc', 'BtnGreen_mc', 'BtnYellowSelected_mc',
      'BtnRedSelected_mc', 'BtnPinkSelected_mc', 'BtnBlueSelected_mc', 'BtnGreenSelected_mc', 'BtnBasic_mc',
      'BtnRandom_mc', 'ControlTextEN_mc', 'CasualTextEN_mc', 'HardcoreTextEN_mc', 'PressKeyAnim_mc',
      'Shuttle01BodyPreview_mc', 'Shuttle01EnginePreview_mc', 'Shuttle02BodyPreview_mc',
      'Shuttle02EnginePreview_mc', 'Shuttle03BodyPreview_mc', 'Shuttle03EnginePreview_mc',
      'Shuttle04BodyPreview_mc', 'Shuttle04EnginePreview_mc', 'Tutorial01_mc', 'Tutorial02_mc',
      'Tutorial03_mc', 'Tutorial04_mc', 'Tutorial05_mc', 'Tutorial06_mc',
    ];
  }
}
