import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import sharp from 'sharp';
import { describe, expect, it } from 'vitest';
import {
  TIER_NAMES,
  TIER_ZOOM,
  parseManifest,
  type Manifest,
} from '../../src/engine/assets/schemas';
import { ATLAS_EXTRUDE, composePage, packItems } from './atlas';
import { makePaths } from './decompile';
import {
  alphaBounds,
  alphaMaskBits,
  checkCanvasSize,
  computeBuildHash,
  cropRaw,
  groupOf,
  loadAlphaMaskSymbols,
  loadGroups,
  loadOverrides,
  spritesDir,
  upscaleNearest,
  type Raw,
} from './sprites';
import { loadSymbols } from './types';
import { BLACKLIST_NAMES, buildWhitelist, isBlacklisted } from './whitelist';

const ROOT = process.cwd();
const P = makePaths(ROOT);
const MANIFEST = join(ROOT, 'assets', 'manifest.json');
// Generated by `npm run extract` (steps symbols + sprites); without it the data checks are skipped.
const hasData = existsSync(MANIFEST) && existsSync(join(P.extractDir, 'symbols.json'));
const dataIt = it.skipIf(!hasData);

function rawOf(w: number, h: number, alphaAt: (x: number, y: number) => number): Raw {
  const data = Buffer.alloc(w * h * 4);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const i = (y * w + x) * 4;
      data[i] = 10 + x;
      data[i + 1] = 20 + y;
      data[i + 2] = 30;
      data[i + 3] = alphaAt(x, y);
    }
  }
  return { data, w, h };
}

describe('sprite helpers', () => {
  it('upscaleNearest: every pixel becomes a k x k block; k = 1 is the identity', () => {
    const src = rawOf(3, 2, (x, y) => 40 + x * 10 + y);
    expect(upscaleNearest(src, 1)).toBe(src);
    const up = upscaleNearest(src, 3);
    expect([up.w, up.h]).toEqual([9, 6]);
    for (let y = 0; y < 6; y++) {
      for (let x = 0; x < 9; x++) {
        const a = (y * 9 + x) * 4;
        const b = (Math.floor(y / 3) * 3 + Math.floor(x / 3)) * 4;
        expect([...up.data.subarray(a, a + 4)]).toEqual([...src.data.subarray(b, b + 4)]);
      }
    }
  });

  it('groupOf: first matching rule wins, $1 is substituted', () => {
    const cfg = {
      default: 'game-common',
      rules: [
        { group: 'level-$1', match: '^Level(\\d\\d)BG_mc$' },
        { group: 'ui', match: '^Btn' },
      ],
    };
    expect(groupOf('Level07BG_mc', cfg)).toBe('level-07');
    expect(groupOf('BtnPlay_mc', cfg)).toBe('ui');
    expect(groupOf('Coin_mc', cfg)).toBe('game-common');
  });

  it('the real groups.json sends symbols to the documented groups', () => {
    const cfg = loadGroups(ROOT);
    expect(groupOf('Level20FG_mc', cfg)).toBe('level-20');
    expect(groupOf('Font:font01', cfg)).toBe('ui');
    expect(groupOf('BtnPlay_mc', cfg)).toBe('ui');
    expect(groupOf('Shuttle01Body_mc', cfg)).toBe('shuttles');
    expect(groupOf('Indicator01Color01_mc', cfg)).toBe('shuttles');
    expect(groupOf('PassengerBlue01Idle_mc', cfg)).toBe('passengers');
    expect(groupOf('SmokeEffect01_mc', cfg)).toBe('effects');
    expect(groupOf('Coin_mc', cfg)).toBe('game-common');
  });

  it('alphaBounds finds the opaque box and null for an empty image', () => {
    const r = rawOf(6, 5, (x, y) => (x >= 2 && x <= 3 && y === 1 ? 1 : 0));
    expect(alphaBounds(r)).toEqual([2, 1, 2, 1]);
    expect(alphaBounds(rawOf(3, 3, () => 0))).toBeNull();
  });

  it('cropRaw copies pixels and leaves out-of-range parts transparent', () => {
    const r = rawOf(4, 4, () => 255);
    const c = cropRaw(r, -1, 2, 3, 3);
    expect(c.w).toBe(3);
    // Row 0 = source row 2, column 0 lies outside (x = -1) -> transparent.
    expect(c.data[3]).toBe(0);
    expect(c.data[(0 * 3 + 1) * 4]).toBe(10); // source (0, 2)
    expect(c.data[(0 * 3 + 1) * 4 + 3]).toBe(255);
    // Row 2 = source row 4, outside -> transparent.
    expect(c.data[(2 * 3 + 1) * 4 + 3]).toBe(0);
  });

  it('alphaMaskBits: 1 bit per pixel, MSB first, rows byte-aligned', () => {
    const r = rawOf(10, 2, (x, y) => (x === 0 || (x === 9 && y === 1) ? 5 : 0));
    const bits = alphaMaskBits(r);
    expect(bits.length).toBe(4); // 2 bytes per row
    expect([...bits]).toEqual([0b10000000, 0, 0b10000000, 0b01000000]);
  });

  it('checkCanvasSize accepts +-1 px and names the frame otherwise', () => {
    const rect = { xMin: -1, yMin: -1, xMax: 11.4, yMax: 5 };
    const ok: Raw = { data: Buffer.alloc(0), w: 26, h: 12 };
    expect(() => checkCanvasSize('A#0', ok, rect, 2)).not.toThrow();
    expect(() => checkCanvasSize('A#0', { ...ok, w: 30 }, rect, 2)).toThrow(/A#0/);
  });

  it('packItems never overlaps, honours padding + extrude and composePage extrudes edges', () => {
    const items = Array.from({ length: 40 }, (_, i) => ({
      id: i,
      w: 20 + (i % 7) * 9,
      h: 15 + (i % 5) * 11,
      hash: `h${i}`,
    }));
    const { bins, placed } = packItems(items, 256, 2, 1);
    expect(placed).toHaveLength(items.length);
    expect(bins.length).toBeGreaterThan(1);
    for (const b of bins) {
      expect(b.w).toBeLessThanOrEqual(256);
      expect(b.h).toBeLessThanOrEqual(256);
    }
    for (const a of placed) {
      const ia = items[a.id] as (typeof items)[number];
      const bin = bins[a.bin] as (typeof bins)[number];
      expect(a.x - 1).toBeGreaterThanOrEqual(0);
      expect(a.x + ia.w + 1).toBeLessThanOrEqual(bin.w);
      expect(a.y + ia.h + 1).toBeLessThanOrEqual(bin.h);
      for (const b of placed) {
        if (a === b || a.bin !== b.bin) continue;
        const ib = items[b.id] as (typeof items)[number];
        // Extruded rectangles are `padding` (2) apart.
        const sepX = a.x - 1 >= b.x + ib.w + 1 + 2 || b.x - 1 >= a.x + ia.w + 1 + 2;
        const sepY = a.y - 1 >= b.y + ib.h + 1 + 2 || b.y - 1 >= a.y + ia.h + 1 + 2;
        expect(sepX || sepY).toBe(true);
      }
    }
    const page = composePage(
      8,
      8,
      [
        {
          rgba: Buffer.from([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]),
          w: 2,
          h: 2,
          x: 3,
          y: 3,
        },
      ],
      ATLAS_EXTRUDE,
    );
    const px = (x: number, y: number): number[] => [
      ...page.subarray((y * 8 + x) * 4, (y * 8 + x) * 4 + 4),
    ];
    expect(px(3, 3)).toEqual([1, 2, 3, 4]);
    expect(px(2, 3)).toEqual([1, 2, 3, 4]); // left extrude
    expect(px(2, 2)).toEqual([1, 2, 3, 4]); // corner extrude
    expect(px(5, 5)).toEqual([13, 14, 15, 16]);
    expect(px(1, 1)).toEqual([0, 0, 0, 0]);
  });

  it('packItems rejects a frame that cannot fit a page', () => {
    expect(() => packItems([{ id: 0, w: 5000, h: 10, hash: 'x' }])).toThrow(/does not fit/);
  });

  it('blacklist covers the documented names and all LevelNNPhysic_mc', () => {
    expect(BLACKLIST_NAMES).toContain('AGIntro_mc');
    expect(isBlacklisted('Level01Physic_mc')).toBe(true);
    expect(isBlacklisted('Level01BG_mc')).toBe(false);
  });

  it('alphamask-symbols.json matches the animations used by ShuttleView.as', () => {
    const src = join(P.refAs3, 'ru', 'alientransporter', 'views', 'ShuttleView.as');
    if (!existsSync(src)) return;
    const used = new Set<string>();
    for (const m of readFileSync(src, 'utf8').matchAll(/addAnimationFromCache\("([^"]+)"/g)) {
      used.add(m[1] as string);
    }
    expect([...loadAlphaMaskSymbols(ROOT)].sort()).toEqual([...used].sort());
  });
});

function manifest(): Manifest {
  return parseManifest(readFileSync(MANIFEST, 'utf8'));
}

describe('sprites manifest (needs `npm run extract`)', () => {
  dataIt('passes the zod schema and the build hash matches', () => {
    const m = manifest();
    expect(m.buildHash).toBe(computeBuildHash(m));
    expect(m.frames.length).toBeGreaterThan(5000);
    expect(m.frames.length).toBeLessThanOrEqual(65536);
  });

  dataIt('texId order: symbols sorted by name, frames contiguous and 0-based keys', () => {
    const m = manifest();
    const names = Object.keys(m.symbols);
    expect([...names].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0))).toEqual(names);
    let next = 0;
    for (const name of names) {
      const s = m.symbols[name]!;
      expect(s.firstTexId).toBe(next);
      for (let i = 0; i < s.frames; i++) expect(m.frames[next + i]!.key).toBe(`${name}#${i}`);
      next += s.frames;
    }
    // The `fontglyphs` step (T1.9e) appends the glyph frames `Font:<font>#<charCode>` after the symbol frames.
    const glyphs = m.frames.slice(next);
    for (const g of glyphs) expect(g.key, g.key).toMatch(/^Font:font\w+#[1-9]\d*$/);
    expect(next + glyphs.length).toBe(m.frames.length);
  });

  dataIt('every whitelisted symbol has all its frames in every tier; blacklist is absent', () => {
    const m = manifest();
    const symbols = loadSymbols(P.extractDir);
    const wl = buildWhitelist(ROOT, symbols);
    const overrides = loadOverrides(ROOT);
    const byId = new Map(symbols.map((s) => [s.id, s]));
    expect(wl.symbols.length).toBeGreaterThan(400);
    for (const w of wl.symbols) {
      const ref = m.symbols[w.name];
      expect(ref, w.name).toBeDefined();
      expect(ref!.frames, w.name).toBe(byId.get(w.id)!.frames);
      const maxTier = overrides[w.name]?.maxTier;
      for (let i = 0; i < ref!.frames; i++) {
        const f = m.frames[ref!.firstTexId + i]!;
        for (const tier of TIER_NAMES) {
          const t = f.tiers[tier];
          expect(m.atlases[tier][t.atlas], `${f.key} @${tier}`).toBeDefined();
          const expectedScale = maxTier
            ? Math.min(TIER_ZOOM[tier], TIER_ZOOM[maxTier]) / TIER_ZOOM[tier]
            : 1;
          expect(t.scale ?? 1, `${f.key} @${tier}`).toBeCloseTo(expectedScale, 9);
        }
      }
    }
    for (const name of BLACKLIST_NAMES) expect(m.symbols[name], name).toBeUndefined();
    for (const name of Object.keys(m.symbols))
      expect(/^Level\d\dPhysic_mc$/.test(name)).toBe(false);
  });

  dataIt('Coin_mc: 30 frames, origin1x ~ (11.9, 11.95)', () => {
    const m = manifest();
    expect(m.symbols.Coin_mc!.frames).toBe(30);
    const f = m.frames[m.symbols.Coin_mc!.firstTexId]!;
    expect(f.origin1x[0]).toBeCloseTo(11.9, 2);
    expect(f.origin1x[1]).toBeCloseTo(11.95, 2);
    expect(f.size1x[0]).toBeCloseTo(24.4, 2);
    expect(f.size1x[1]).toBeCloseTo(23.65, 2);
  });

  dataIt('MainMenuBG_mc#0: size1x (800, 600), origin (0, 0)', () => {
    const m = manifest();
    const f = m.frames[m.symbols.MainMenuBG_mc!.firstTexId]!;
    expect(f.size1x).toEqual([800, 600]);
    expect(f.origin1x[0]).toBeCloseTo(0, 6);
    expect(f.origin1x[1]).toBeCloseTo(0, 6);
  });

  dataIt('level layers are cropped to 800x600 logical: Level01BG_mc#0 is 1600x1200 at 2x', () => {
    const m = manifest();
    const f = m.frames[m.symbols.Level01BG_mc!.firstTexId]!;
    expect(f.size1x).toEqual([800, 600]);
    expect(f.origin1x).toEqual([0, 0]);
    expect(f.tiers['2x'].rect.slice(2)).toEqual([1600, 1200]);
    expect(f.tiers['2x'].trim).toEqual([0, 0, 1600, 1200]);
    expect(f.tiers['1x'].rect.slice(2)).toEqual([800, 600]);
    expect(f.tiers['3x'].rect.slice(2)).toEqual([2400, 1800]);
    expect(f.group).toBe('level-01');
  });

  dataIt(
    'at most 4 atlases at 2x for every group except level-* (else lists the top symbols)',
    () => {
      const m = manifest();
      const pages: Record<string, number> = {};
      for (const key of Object.keys(m.atlases['2x'])) {
        const group = key.replace(/-\d+$/, '');
        pages[group] = (pages[group] ?? 0) + 1;
      }
      const over = Object.entries(pages).filter(([g, n]) => !g.startsWith('level-') && n > 4);
      if (over.length) {
        const area: Record<string, number> = {};
        for (const f of m.frames) {
          if (over.some(([g]) => g === f.group)) {
            const [, , w, h] = f.tiers['2x'].rect;
            area[f.key.split('#')[0]!] = (area[f.key.split('#')[0]!] ?? 0) + w * h;
          }
        }
        const top = Object.entries(area)
          .sort((a, b) => b[1] - a[1])
          .slice(0, 20)
          .map(([n, a]) => `${n}: ${(a / 1e6).toFixed(2)} Mpx`);
        throw new Error(`groups over 4 atlases at 2x: ${JSON.stringify(over)}\n${top.join('\n')}`);
      }
      expect(over).toEqual([]);
    },
  );

  dataIt('every rect lies inside its atlas page and every atlas file exists', async () => {
    const m = manifest();
    const sizes = new Map<string, { w: number; h: number }>();
    for (const tier of TIER_NAMES) {
      for (const [key, rel] of Object.entries(m.atlases[tier])) {
        const file = join(ROOT, 'assets', rel);
        expect(existsSync(file), file).toBe(true);
        const meta = await sharp(file).metadata();
        expect(meta.width).toBeLessThanOrEqual(4096);
        expect(meta.height).toBeLessThanOrEqual(4096);
        sizes.set(`${tier}/${key}`, { w: meta.width, h: meta.height });
      }
    }
    for (const f of m.frames) {
      for (const tier of TIER_NAMES) {
        const t = f.tiers[tier];
        const page = sizes.get(`${tier}/${t.atlas}`)!;
        const [x, y, w, h] = t.rect;
        expect(x, f.key).toBeGreaterThanOrEqual(0);
        expect(y, f.key).toBeGreaterThanOrEqual(0);
        expect(x + w, f.key).toBeLessThanOrEqual(page.w);
        expect(y + h, f.key).toBeLessThanOrEqual(page.h);
      }
    }
  });

  dataIt(
    'atlas pixels equal the trimmed source PNG (straight alpha, correct placement)',
    async () => {
      const m = manifest();
      const symbols = loadSymbols(P.extractDir);
      const coin = symbols.find((s) => s.className === 'Coin_mc')!;
      const f = m.frames[m.symbols.Coin_mc!.firstTexId + 5]!;
      const dir = readdirSync(spritesDir(P, 2)).find((n) =>
        n.startsWith(`DefineSprite_${coin.id}_`),
      )!;
      const src = await sharp(join(spritesDir(P, 2), dir, '6.png'))
        .ensureAlpha()
        .raw()
        .toBuffer({ resolveWithObject: true });
      const t = f.tiers['2x'];
      const page = await sharp(join(ROOT, 'assets', m.atlases['2x'][t.atlas]!))
        .ensureAlpha()
        .raw()
        .toBuffer({ resolveWithObject: true });
      const [rx, ry, rw, rh] = t.rect;
      const [tx, ty] = t.trim;
      expect([rw, rh]).toEqual([t.trim[2], t.trim[3]]);
      for (let y = 0; y < rh; y++) {
        for (let x = 0; x < rw; x++) {
          for (let c = 0; c < 4; c++) {
            const a = page.data[((ry + y) * page.info.width + rx + x) * 4 + c];
            const s = src.data[((ty + y) * src.info.width + tx + x) * 4 + c];
            if (c < 3 && src.data[((ty + y) * src.info.width + tx + x) * 4 + 3] === 0) continue;
            expect(a).toBe(s);
          }
        }
      }
    },
  );

  dataIt('alpha masks: 1x, untrimmed, alpha > 0, only for the ShuttleView symbols', async () => {
    const m = manifest();
    const bin = readFileSync(join(ROOT, 'assets', 'data', 'alphamasks.bin'));
    const maskSymbols = new Set(loadAlphaMaskSymbols(ROOT));
    for (const f of m.frames) {
      const name = f.key.split('#')[0]!;
      expect(f.mask !== undefined, f.key).toBe(maskSymbols.has(name));
      if (f.mask) {
        expect(f.mask.offset + ((f.mask.w + 7) >> 3) * f.mask.h, f.key).toBeLessThanOrEqual(
          bin.length,
        );
      }
    }
    // Recompute one mask from the raw 1x export.
    const symbols = loadSymbols(P.extractDir);
    const sym = symbols.find((s) => s.className === 'Shuttle01Body_mc')!;
    const dir = readdirSync(spritesDir(P, 1)).find((n) => n.startsWith(`DefineSprite_${sym.id}_`))!;
    const raw = await sharp(join(spritesDir(P, 1), dir, '1.png'))
      .ensureAlpha()
      .raw()
      .toBuffer({ resolveWithObject: true });
    const expected = alphaMaskBits({ data: raw.data, w: raw.info.width, h: raw.info.height });
    const f = m.frames[m.symbols.Shuttle01Body_mc!.firstTexId]!;
    expect(f.mask!.w).toBe(raw.info.width);
    expect(f.mask!.h).toBe(raw.info.height);
    expect(bin.subarray(f.mask!.offset, f.mask!.offset + expected.length).equals(expected)).toBe(
      true,
    );
    expect(expected.some((b) => b !== 0)).toBe(true);
  });

  dataIt('bitmap fonts are packed into the ui group as Font:<name>', () => {
    const m = manifest();
    const f = m.frames[m.symbols['Font:font01']!.firstTexId]!;
    expect(f.group).toBe('ui');
    expect(f.origin1x).toEqual([0, 0]);
    // T5.6: the font bitmap is replicated at 2x/3x (real pixels of the tier), not stretched from the 1x raster by `scale`
    expect(f.tiers['2x'].scale).toBeUndefined();
    expect(f.tiers['3x'].scale).toBeUndefined();
    expect(f.tiers['2x'].rect.slice(2)).toEqual(f.tiers['1x'].rect.slice(2).map((v) => v * 2));
    expect(f.tiers['3x'].rect.slice(2)).toEqual(f.tiers['1x'].rect.slice(2).map((v) => v * 3));
  });

  dataIt('T5.6: the UI of 1:1 bitmaps (indicator, buttons, captions) is drawn from real 3x pixels, never a stretched lower tier', () => {
    const m = manifest();
    const names = [
      'Indicator01Color01_mc',
      'Indicator04Color05_mc',
      'BtnPlay_mc',
      'BtnMainMenu_mc',
      'BtnApply_mc',
      'BtnRestart_mc',
      'CasualTextEN_mc',
      'ConfirmTextEN_mc',
      'IconShuttleBlue_mc',
      'IconPassengerPirate_mc',
      'PausePopupBG_mc',
      'LivesIcon_mc',
      'Font:font04',
    ];
    for (const name of names) {
      const sym = m.symbols[name]!;
      for (let i = 0; i < sym.frames; i++) {
        const f = m.frames[sym.firstTexId + i]!;
        for (const tier of ['2x', '3x'] as const) {
          const t = f.tiers[tier];
          expect(t.scale, `${name}#${i} ${tier}`).toBeUndefined();
          // replicated pixels: the tier rectangle is the 1x rectangle times the zoom
          expect(t.rect[2], `${name}#${i} ${tier} w`).toBe(f.tiers['1x'].rect[2] * TIER_ZOOM[tier]);
          expect(t.rect[3], `${name}#${i} ${tier} h`).toBe(f.tiers['1x'].rect[3] * TIER_ZOOM[tier]);
        }
      }
    }
  });

  dataIt('T5.6: the pixels of a replicated frame at 3x are the pixels of the 1x frame, 3x3 blocks', async () => {
    const m = manifest();
    const f = m.frames[m.symbols['Indicator01Color01_mc']!.firstTexId]!;
    const grab = async (tier: '1x' | '3x'): Promise<Raw> => {
      const t = f.tiers[tier];
      const { data, info } = await sharp(join(ROOT, 'assets', m.atlases[tier][t.atlas]!))
        .extract({ left: t.rect[0], top: t.rect[1], width: t.rect[2], height: t.rect[3] })
        .ensureAlpha()
        .raw()
        .toBuffer({ resolveWithObject: true });
      return { data, w: info.width, h: info.height };
    };
    const one = await grab('1x');
    const three = await grab('3x');
    expect(three).toMatchObject({ w: one.w * 3, h: one.h * 3 });
    let bad = 0;
    for (let y = 0; y < three.h; y++) {
      for (let x = 0; x < three.w; x++) {
        const a = (y * three.w + x) * 4;
        const b = ((Math.floor(y / 3) * one.w) + Math.floor(x / 3)) * 4;
        for (let c = 0; c < 4; c++) if (three.data[a + c] !== one.data[b + c]) bad++;
      }
    }
    expect(bad).toBe(0);
  });
});
